apiVersion: v2
name: geokode
description: High-performance geocoding server
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - geocoding
  - geospatial
  - reverse-geocoding
maintainers:
  - name: GeoLang
