replicaCount: 1

image:
  repository: geokode
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: geokode.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 5Gi

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "2"
    memory: 2Gi

env:
  RUST_LOG: "info,geokode=debug"

nodeSelector: {}
tolerations: []
affinity: {}
